Test case that is failing on my system. Found it because I was getting
Fatal error: Cannot redeclare Mock_Kernel_19df64f5::serialize() in /usr/local/zend/share/pear/PHPUnit/Framework/MockObject/Generator.php(170) : eval()'d code on line 474

when attempting to getMock of https://github.com/fabpot/symfony/blob/master/src/Symfony/Component/HttpKernel/Kernel.php